version: "3"

services:
  abci0:
    container_name: abci0
    image: "tendermint-app"
    ports:
      - "26658"
      - "8088"
    volumes:
      - ./build:/tendermint:Z
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app node0/config/genesis.json
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "tendermint-app"
    ports:
      - "26658"
      - "8088"
    volumes:
      - ./build:/tendermint:Z
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app node1/config/genesis.json
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    container_name: abci2
    image: "tendermint-app"
    ports:
      - "26658"
      - "8088"
    volumes:
      - ./build:/tendermint:Z
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app node2/config/genesis.json
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    container_name: abci3
    image: "tendermint-app"
    ports:
      - "26658"
      - "8088"
    volumes:
      - ./build:/tendermint:Z
    build:
      context: .
      dockerfile: ../xnode-app/Dockerfile
    command: /tendermint-app node3/config/genesis.json
    networks:
      localnet:
        ipv4_address: 192.167.10.9

  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
      - "6060:6060"
      - "27000:26660"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy-app=tcp://abci0:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "tendermint/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy-app=tcp://abci1:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    image: "tendermint/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy-app=tcp://abci2:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    image: "tendermint/localnode"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy-app=tcp://abci3:26658
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  xnode0:
    container_name: xnode0
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.167.10.6 http://192.167.10.2:26657 # abci0 node0
    networks:
      localnet:
        ipv4_address: 192.167.10.10

  xnode1:
    container_name: xnode1
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.167.10.7 http://192.167.10.3:26657 # abci1 node1
    networks:
      localnet:
        ipv4_address: 192.167.10.11

  xnode2:
    container_name: xnode2
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.167.10.8 http://192.167.10.4:26657 # abci2 node2
    networks:
      localnet:
        ipv4_address: 192.167.10.12

  xnode3:
    container_name: xnode3
    image: "xnode"
    build:
      context: .
      dockerfile: ../data-mock/Dockerfile
    command: data-provider.js 192.167.10.9 http://192.167.10.5:26657 # abci3 node3
    networks:
      localnet:
        ipv4_address: 192.167.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
